(function(g){var window=this;var B3=function(a){var b={languageCode:a.u,languageName:a.A,displayName:g.aA(a),kind:a.w,name:a.B,id:a.H,is_servable:a.D,is_default:a.isDefault,is_translateable:a.isTranslateable,vss_id:a.C};a.o&&(b.translationLanguage=a.o);return b},C3=function(a){return a.o?a.o.languageCode:a.u},ipa=function(a,b){var c=new g.$z;
c.u=a.u;c.A=a.A;c.B=a.B;c.w=a.w;c.isDefault=!1;c.D=a.D;c.isTranslateable=a.isTranslateable;c.C=a.C;c.G=a.G;c.o=b;return c},jpa=function(){this.u=[];
this.o=[]},D3=function(a,b){return b?a.o.concat(a.u):a.o},E3=function(a,b){switch(b.w){case "asr":var c=a.u;
g.Va(c,(0,g.x)(b.dr,b))||c.push(b);break;default:c=a.o,g.Va(c,(0,g.x)(b.dr,b))||c.push(b)}},F3=function(a){g.A.call(this);
this.Ya=a;this.u=new jpa;this.B=[]},G3=function(a,b,c){F3.call(this,a);
this.o=null;this.B=b.Mu;this.A=c},H3=function(){this.o=[]},I3=function(a,b,c,d,e,f){g.A.call(this);
this.J=a;this.A=b;this.U=b.P();this.B=new H3;this.o=null;this.D=d;this.K=f;this.u=this.w=null;this.N=c;this.C=e||!1;this.G=new g.J(this.Vw,1E3,this);g.B(this,this.G);this.H=new g.P(this);g.B(this,this.H);this.H.M(b,"SEEK_COMPLETE",this.Mx);this.Mx();this.Vw()},J3=function(a,b){b-=a.A.vb();
var c=a.o;a.o=g.Ta(a.N.Gf(b).o);c!=a.o&&a.K&&a.K()},K3=function(a,b){var c=g.Uw(g.bz(b,a.J,{})),d={format:"RAW",
withCredentials:!0};a.C&&(d.responseType="arraybuffer");a.u=g.Sp(c,d,3,100).then((0,g.x)(a.wL,a));a.w=b;c=a.B;d=a.w.o[0].u;var e=g.lb(c.o,d);0<=e||0>e&&1==(-e-1)%2||(e=-e-1,0<e&&1==d-c.o[e-1]&&e<c.o.length&&1==c.o[e]-d?(g.ab(c.o,e),g.ab(c.o,e-1)):0<e&&1==d-c.o[e-1]?c.o[e-1]=d:e<c.o.length&&1==c.o[e]-d?c.o[e]=d:(g.ib(c.o,e,0,d),g.ib(c.o,e+1,0,d)))},L3=function(a,b){F3.call(this,b.P());
this.o=a;this.D=b;this.A=null;this.w=!1;this.C=g.Ky(this.D.P())&&!this.o.u},M3=function(a,b){var c=[],d;
for(d in a.o.o){var e=a.o.o[d];if(g.dR(e,b||null)){var f="en",k="English",l=".en",m="";if(e=e.info.captionTrack)f=e.languageCode,k=e.displayName,l=e.vssId,m=e.kind;c.push(new g.$z({id:d,languageCode:f,languageName:k,is_servable:!0,is_default:!0,is_translateable:!1,vss_id:l,kind:m}))}}return c},kpa=function(a,b){return null!=b&&b in a.o.o?a.o.o[b]:null},N3=function(a,b,c){var d=[],e;
for(e in a.o.o){var f=a.o.o[e];if(g.dR(f,c||null)){var k=f.info.captionTrack;k&&k.languageCode==b&&d.push(f)}}return d.length?d[0]:null},O3=function(a,b,c,d,e){F3.call(this,e||null);
c=c||g.Zo(a).hl||"";c=c.split("_").join("-");this.w=g.ap(a,{hl:c});this.A=b;this.C=!!d;this.D={};this.o=null},P3=function(a,b,c,d,e,f,k){f=void 0===f?!1:f;
k=void 0===k?null:k;g.sE.call(this,a,a+b,{priority:c,namespace:"captions"});this.windowId=d;this.text=e;this.A=f;this.o=k},Q3=function(a,b,c,d,e){g.sE.call(this,a,a+b,{priority:c,
namespace:"captions"});this.id=d;this.params=e;this.o=[]},R3=function(a,b){g.B(a,b);
a.o.push(b)},T3=function(a){a=void 0===a?{}:a;
var b="_"+S3++;return new Q3(0,0x8000000000000,0,b,a)},V3=function(a,b,c,d,e,f){var k={};
g.Pa(k,b);g.Pa(k,a.params);g.Pa(k,c);var l={};g.Pa(l,b.wb);a.params.wb&&g.Pa(l,a.params.wb);g.Pa(l,c.wb);k.wb=l;g.S.call(this,{F:"div",I:"caption-window",O:{id:"caption-window-"+a.id,dir:1==k.Gd?"rtl":"ltr",tabindex:"0","aria-live":"assertive",lang:k.lang},L:[{F:"span",I:"captions-text",O:{style:"word-wrap: normal; display: block;"}}]});this.G=[];this.V=!1;this.B=a;this.da=this.W=null;this.Na=e;this.Ma=f;this.H=null;this.ba=.96*e;this.ya=.96*f;this.w=k;this.Ja=c;this.D=this.u["captions-text"];this.Da=
null!=this.D.style["box-decoration-break"]||null!=this.D.style["-webkit-box-decoration-break"];this.aa=d/360*16;this.type=0;this.oa=this.aa*U3(l);a=new g.dN(this.element,!0);g.B(this,a);a.subscribe("dragstart",this.JG,this);a.subscribe("dragmove",this.IG,this);a.subscribe("dragend",this.HG,this);this.xa=this.ra=0;b="";this.w.windowOpacity&&(a=g.w0(this.w.windowColor),b="rgba("+a[0]+","+a[1]+","+a[2]+","+this.w.windowOpacity+")");a={"background-color":b,display:!1===this.w.isVisible?"none":"","text-align":lpa[this.w.textAlign]};
this.Da&&(a["border-radius"]=b?this.oa/8+"px":"");if(this.C=2==this.B.params.Gd||3==this.B.params.Gd)b=this.element,c="vertical-rl",1==this.w.it&&(c="vertical-lr"),g.Ed&&(c="vertical-lr"==c?"tb-lr":"tb-rl"),g.kh(b,"-o-writing-mode",c),g.kh(b,"-webkit-writing-mode",c),g.kh(b,"writing-mode",c),g.kh(b,"text-orientation","upright"),g.L(b,"ytp-vertical-caption"),3==this.B.params.Gd&&(g.kh(b,"text-orientation",""),g.kh(b,"transform","rotate(180deg)"));g.kh(this.element,a);switch(this.w.uf){case 0:case 1:case 2:g.L(this.element,
"ytp-caption-window-top");break;case 6:case 7:case 8:g.L(this.element,"ytp-caption-window-bottom")}},U3=function(a){var b=1+.25*(a.fontSizeIncrement||0);
if(0==a.offset||2==a.offset)b*=.8;return b},W3=function(a,b){var c={},d=b.background?b.background:a.w.wb.background;
if(null!=b.backgroundOpacity||b.background){var e=null!=b.backgroundOpacity?b.backgroundOpacity:a.w.wb.backgroundOpacity;d=g.w0(d);c.background="rgba("+d[0]+","+d[1]+","+d[2]+","+e+")";a.Da&&(c["box-decoration-break"]="clone",c["border-radius"]=a.oa/8+"px")}if(null!=b.fontSizeIncrement||null!=b.offset)c["font-size"]=a.aa*U3(b)+"px";d=1;e=b.color||a.w.wb.color;if(b.color||null!=b.textOpacity)e=g.w0(e),d=null==b.textOpacity?a.w.wb.textOpacity:b.textOpacity,e="rgba("+e[0]+","+e[1]+","+e[2]+","+d+")",
c.color=e,c.fill=e;var f=b.charEdgeStyle;0==f&&(f=null);if(f){e="rgba(34, 34, 34, "+d+")";var k="rgba(204, 204, 204, "+d+")";b.qp&&(k=e=b.qp);var l=a.aa/16/2,m=Math.max(l,1),n=Math.max(2*l,1),q=Math.max(3*l,1),t=Math.max(5*l,1);d=[];switch(f){case 4:for(;q<=t;q+=l)d.push(n+"px "+n+"px "+q+"px "+e);break;case 1:n=2<=window.devicePixelRatio?.5:1;for(f=m;f<=q;f+=n)d.push(f+"px "+f+"px "+e);break;case 2:d.push(m+"px "+m+"px "+k);d.push("-"+m+"px -"+m+"px "+e);break;case 3:for(q=0;5>q;q++)d.push("0 0 "+
n+"px "+e)}c["text-shadow"]=d.join(", ")}e="";switch(b.fontFamily){case 1:e='"Courier New", Courier, "Nimbus Mono L", "Cutive Mono", monospace';break;case 2:e='"Times New Roman", Times, Georgia, Cambria, "PT Serif Caption", serif';break;case 3:e='"Deja Vu Sans Mono", "Lucida Console", Monaco, Consolas, "PT Mono", monospace';break;case 5:e='"Comic Sans MS", Impact, Handlee, fantasy';break;case 6:e='"Monotype Corsiva", "URW Chancery L", "Apple Chancery", "Dancing Script", cursive';break;case 7:e=g.Cp()?
'"Carrois Gothic SC", sans-serif-smallcaps':'"Arial Unicode Ms", Arial, Helvetica, Verdana, "Marcellus SC", sans-serif';break;case 0:case 4:e='"YouTube Noto", Roboto, "Arial Unicode Ms", Arial, Helvetica, Verdana, "PT Sans Caption", sans-serif'}e&&(c["font-family"]=e);e=b.offset;null==e&&(e=a.w.wb.offset);switch(e){case 0:c["vertical-align"]="sub";break;case 2:c["vertical-align"]="super"}7==b.fontFamily&&(c["font-variant"]="small-caps");b.bold&&(c["font-weight"]="bold");b.te&&(c["font-style"]="italic");
b.underline&&(c["text-decoration"]="underline");b.wE&&(c.visibility="hidden");1==b.yE&&a.C&&(c["text-combine-upright"]="all",c["text-orientation"]="mixed",e=g.wu||g.My,3==a.B.params.Gd?c.transform=e?"rotate(90deg)":"rotate(180deg)":e&&(c.transform="rotate(-90deg)"));if(1==b.Be||2==b.Be||3==b.Be||4==b.Be||5==b.Be)if(g.wu)c["font-weight"]="bold";else switch(c["text-emphasis-style"]="filled circle",c["text-emphasis-color"]="currentcolor",c["webkit-text-emphasis"]="filled circle",b.Be){case 4:case 3:c["text-emphasis-position"]=
"under left";c["webkit-text-emphasis-position"]="under left";break;case 5:case 2:c["text-emphasis-position"]="over right",c["webkit-text-emphasis-position"]="over right"}return c},X3=function(a){a.H=g.Ld("SPAN");
g.kh(a.H,{display:"block"});g.L(a.H,"caption-visual-line");a.D.appendChild(a.H)},Y3=function(a,b){var c=g.Ld("SPAN");
g.kh(c,{display:"inline-block","white-space":"pre-wrap"});g.kh(c,W3(a,b));c.classList.add("ytp-caption-segment");a.H.appendChild(c);c.previousElementSibling&&(g.kh(c.previousElementSibling,{"border-top-right-radius":"0","border-bottom-right-radius":"0"}),g.kh(c,{"border-top-left-radius":"0","border-bottom-left-radius":"0"}));return c},Z3=function(a,b,c){a.V=a.V||!!c;
var d={};g.Pa(d,a.w.wb);g.Pa(d,c||b.o);g.Pa(d,a.Ja.wb);(c=!a.H)&&X3(a);for(var e=a.W&&a.da&&g.Yb(d,a.da)?a.W:Y3(a,d),f="string"===typeof b.text,k=f?b.text.split("\n"):[b.text],l=0;l<k.length;l++){var m=0<l||!b.A,n=k[l];m&&!c?(X3(a),e=Y3(a,d)):m&&c&&(c=!1);n&&(e.appendChild(f?g.Md(n):n),f||"RUBY"!=n.tagName||4!=n.childElementCount||g.wu||!g.oh(n.children[2],"text-emphasis")||(m=a.C?"padding-right":"padding-top",g.oh(n.children[2],"text-emphasis-position")&&(m=a.C?"padding-left":"padding-bottom"),g.Gd?
g.kh(e,m,"1em"):g.kh(e,m,"0.5em")))}a.da=d;a.W=e;a.G.push(b)},$3=function(){},b4=function(){this.w=this.u=this.mode=this.A=0;
this.B=new a4(this);this.C=new a4(this);this.o=[];this.clear()},mpa=function(a,b,c){if(255==a&&255==b||!a&&!b)return{Ol:a,
Pl:b,result:0};a=c4[a];b=c4[b];if(a&128){if(!(b&128)&&0!=c.o&&c.u==b)return{Ol:a,Pl:b,result:1}}else if(b&128&&1<=a&&31>=a)return{Ol:a,Pl:b,result:2};return{Ol:a,Pl:b,result:3}},npa=function(a,b,c,d){255==b&&255==c||!b&&!c?(45==++a.w&&a.reset(),a.B.o.clear(),a.C.o.clear()):(a.w=0,d4(a.B,b,c,d))},opa=function(a,b){a.o.sort(function(e,f){var k=e.time-f.time;
return 0==k?e.order-f.order:k});
for(var c=0;c<a.o.length;c++){var d=a.o[c];a.u=d.time;0==d.type?npa(a,d.Ou,d.Pu,b):1==d.type&&a.A&496&&d4(a.C,d.Ou,d.Pu,b)}a.o.length=0},e4=function(){this.o=0},f4=function(){this.u=this.A=this.o=0},g4=function(){this.timestamp=this.Zd=0},h4=function(a){this.A=[];
for(var b=0;15>=b;b++){this.A[b]=[];for(var c=0;32>=c;c++)this.A[b][c]=new g4}this.o=this.u=this.row=0;this.style=new e4;this.B=a;this.w=0},i4=function(a,b){if(3==a.style.o){for(var c=0,d=0,e=a.B.u+0,f="",k="",l=e,m=1;15>=m;++m){for(var n=!1,q=d?d:1;32>=q;++q){var t=a.A[m][q];
if(0!=t.Zd){0==c&&(c=m,d=q);n=String.fromCharCode(t.Zd);var u=t.timestamp;u<e&&(e=u);t.timestamp=l;k&&(f+=k,k="");f+=n;n=!0}if((0==t.Zd||32==q)&&n){k="\n";break}else if(d&&!n)break}if(c&&!n)break}f&&b.B(c,d,e,l,f)}else for(d=c=0,f=e=a.B.u+0,k=1;15>=k;++k)for(l="",m=1;32>=m;++m)if(q=a.A[k][m],t=q.Zd,0!=t&&(0==c&&(c=k,d=m),n=String.fromCharCode(t),u=q.timestamp,u<=e&&(e=u),l+=n,q.reset()),32==m||0==t)l&&b.B(c,d,e,f,l),e=f,l="",d=c=0},tpa=function(a,b){switch(a){case 0:return ppa[(b&127)-32];
case 1:return qpa[b&15];case 2:return rpa[b&31];case 3:return spa[b&31]}return 0},j4=function(a){return a.A[a.row][a.u]},k4=function(a,b,c){2<=b&&1<a.u&&(--a.u,j4(a).Zd=0);
var d=j4(a);d.timestamp=a.B.u+0;d.Zd=tpa(b,c);32>a.u&&a.u++},l4=function(a,b,c,d){for(var e=0;e<d;e++)for(var f=0;32>=f;f++)a.A[b+e][f].jg(a.A[c+e][f])},m4=function(a,b,c){for(var d=0;d<c;d++)for(var e=0;32>=e;e++)a.A[b+d][e].reset()},n4=function(a){a.row=0<a.o?a.o:1;
a.u=1;m4(a,0,15)},o4=function(a){this.w=a;
this.B=0;this.style=new e4;this.C=new h4(a);this.D=new h4(a);this.G=new h4(a);this.u=this.C;this.A=this.D;this.o=this.u},p4=function(a,b,c){var d=a.u,e=!1;
switch(a.style.get()){case 4:if(0<d.o)break;case 1:case 2:i4(d,c),n4(a.u),n4(a.A),d.row=15,d.o=b,e=!0}a.style.set(3);a.o=d;a.o.style=a.style;a.w.mode=1<<d.w;e?d.u=1:d.o!=b&&(d.o>b?(i4(d,c),m4(d,d.row-d.o,b)):d.row<b&&(b=d.o),d.o=b)},q4=function(a){a.style.set(1);
a.o=a.A;a.o.o=0;a.o.style=a.style;a.w.mode=1<<a.o.w},r4=function(a){a.style.set(4);
a.o=a.G;a.o.style=a.style;a.w.mode=1<<a.o.w},a4=function(a){this.u=a;
this.o=new f4;this.B=0;this.A=new o4(a);this.C=new o4(a);this.w=this.A},d4=function(a,b,c,d){a.o.update();
b=mpa(b,c,a.o);switch(b.result){case 0:return;case 1:case 2:return}var e=b.Ol;c=b.Pl;if(32<=e||!e)a.u.mode&a.u.A&&(b=e,b&128&&(b=127),c&128&&(c=127),a=a.w.o,b&96&&k4(a,0,b),c&96&&k4(a,0,c),0!=b&&0!=c&&3==a.style.o&&i4(a,d));else if(e&16)a:if(!a.o.matches(e,c)&&(b=a.o,b.A=e,b.u=c,b.o=2,b=e&8?a.C:a.A,a.w=b,a.u.mode=1<<(a.B<<2)+(b.B<<1)+(4==b.style.o?1:0),(a.u.mode|1<<(a.B<<2)+(b.B<<1)+(4!=b.style.o?1:0))&a.u.A))if(c&64){d=[11,11,1,2,3,4,12,13,14,15,5,6,7,8,9,10][(e&7)<<1|c>>5&1];a=c&16?4*((c&14)>>1):
0;c=b.o;switch(b.style.get()){case 4:d=c.row;break;case 3:if(d!=c.row){if(d<c.o&&(d=c.o,d==c.row))break;var f=1+c.row-c.o,k=1+d-c.o;l4(c,k,f,c.o);b=f;e=c.o;k<f?(f=k+e-f,0<f&&(b+=f,e-=f)):(f=f+e-k,0<f&&(e-=f));m4(c,b,e)}}c.row=d;c.u=a+1}else switch(e&7){case 1:switch(c&112){case 32:k4(b.o,0,32);break a;case 48:57==c?(d=b.o,j4(d).Zd=0,32>d.u&&d.u++):k4(b.o,1,c&15)}break;case 2:c&32&&k4(b.o,2,c&31);break;case 3:c&32&&k4(b.o,3,c&31);break;case 4:case 5:if(32<=c&&47>=c)switch(c){case 32:q4(b);break;case 33:d=
b.o;1<d.u&&(--d.u,j4(d).Zd=0);break;case 36:d=b.o;b=j4(d);for(a=0;15>=a;a++)for(c=0;32>=c;c++)if(d.A[a][c]==b){for(;32>=c;c++)d.A[a][c].reset();break}break;case 37:p4(b,2,d);break;case 38:p4(b,3,d);break;case 39:p4(b,4,d);break;case 40:k4(b.o,0,32);break;case 41:b.style.set(2);b.o=b.u;b.o.o=0;b.o.style=b.style;b.w.mode=1<<b.o.w;break;case 42:d=b.G;d.o=15;d.style.set(4);n4(d);r4(b);break;case 43:r4(b);break;case 44:a=b.u;switch(b.style.get()){case 1:case 2:case 3:i4(a,d)}m4(a,0,15);break;case 45:b:{a=
b.o;switch(b.style.get()){default:case 2:case 1:break b;case 4:if(15>a.row){++a.row;a.u=1;break b}case 3:}2>a.o&&(a.o=2,a.row<a.o&&(a.row=a.o));b=a.row-a.o+1;i4(a,d);l4(a,b,b+1,a.o-1);m4(a,a.row,1)}break;case 46:m4(b.A,0,15);break;case 47:i4(b.u,d),b.A.updateTime(b.w.u+0),d=b.A,b.A=b.u,b.u=d,q4(b)}break;case 7:switch(c){case 33:case 34:case 35:d=b.o,32<(d.u+=c&3)&&(d.u=32)}}},s4=function(a,b,c,d,e,f,k){var l=f[0],m=k[l.getAttribute("p")];
if(1==m.hd){var n=f[1],q=f[2],t=f[3];l.getAttribute("p");var u=g.Cp();l.getAttribute("t");n.getAttribute("t");q.getAttribute("t");t.getAttribute("t");f=u?g.Ld("DIV"):g.Ld("RUBY");l=l.textContent;var z=g.Ld("SPAN");z.textContent=l;f.appendChild(z);n.getAttribute("p");z=u?g.Ld("DIV"):g.Ld("RP");l=n.textContent;z.textContent=l;f.appendChild(z);k=k[q.getAttribute("p")];l=q.textContent;q=u?g.Ld("DIV"):g.Ld("RT");q.textContent=l;f.appendChild(q);l=k.hd;if(10==l||11==l||12==l||13==l||14==l)if(g.kh(q,"text-emphasis-style",
"filled circle"),g.kh(q,"text-emphasis-color","currentcolor"),g.kh(q,"webkit-text-emphasis","filled circle"),k.hd==k.hd==11||13==k.hd)g.kh(q,"webkit-text-emphasis-position","under left"),g.kh(q,"text-emphasis-position","under left");q=!0;if(4==k.hd||7==k.hd||12==k.hd||14==k.hd)g.kh(f,"ruby-position","over"),g.kh(f,"-webkit-ruby-position","before");else if(5==k.hd||6==k.hd||11==k.hd||13==k.hd)g.kh(f,"ruby-position","under"),g.kh(f,"-webkit-ruby-position","after"),q=!1;t.getAttribute("p");l=t.textContent;
t=u?g.Ld("DIV"):g.Ld("RP");t.textContent=l;f.appendChild(t);u&&(u=q,g.kh(f,{display:"inline-block",position:"relative"}),t=f.firstElementChild.nextElementSibling,g.kh(t,"display","none"),t=t.nextElementSibling,g.kh(t,{"font-size":"0.5em","line-height":"1.2em","text-align":"center",position:"absolute",left:"50%",transform:"translateX(-50%)",width:"400%"}),g.kh(f.lastElementChild,"display","none"),u?(g.kh(f,"padding-top","0.6em"),g.kh(t,"top","0")):(g.kh(f,"padding-bottom","0.6em"),g.kh(t,"bottom",
"0")));return new P3(a,b,e,c,f,d,m)}switch(m.hd){case 9:case 10:m.Be=1;break;case 11:m.Be=2;break;case 12:m.Be=3;break;case 13:m.Be=4;break;case 14:m.Be=5}return new P3(a,b,e,c,l.textContent||"",d,m)},t4=function(){g.A.apply(this,arguments)},u4=function(a){t4.call(this);
this.w={};this.H={};this.J={};this.B="_"+S3++;this.C=a;this.G={};this.u=this.o=null;this.D=!0},v4=function(a,b){var c=a.getAttribute(b);
if(null!=c)return parseFloat(c)},w4=function(a,b){var c=a.getAttribute(b);
if(null!=c)return"1"==c},x4=function(a,b){var c=v4(a,b);
return void 0!=c?c:null},z4=function(a,b){var c=a.getAttribute(b);
if(null!=c)return y4.test(c),c},upa=function(a,b){var c={},d=b.getAttribute("ws");
g.Pa(c,d?a.J[d]:a.C);d=x4(b,"mh");null!=d&&(c.Ei=d);d=x4(b,"ju");null!=d&&(c.textAlign=d);d=x4(b,"pd");null!=d&&(c.Gd=d);d=x4(b,"sd");null!=d&&(c.it=d);d=z4(b,"wfc");null!=d&&(c.windowColor=d);d=v4(b,"wfo");void 0!=d&&(c.windowOpacity=d/255);return c},vpa=function(a,b){var c={},d=b.getAttribute("wp");
d&&g.Pa(c,a.H[d]);d=x4(b,"ap");null!=d&&(c.uf=d);d=v4(b,"cc");null!=d&&(c.gg=d);d=v4(b,"ah");null!=d&&(c.ue=d);d=v4(b,"rc");null!=d&&(c.Wf=d);d=v4(b,"av");null!=d&&(c.Xf=d);return c},wpa=function(a,b,c,d){var e={};
g.Pa(e,vpa(a,b));g.Pa(e,upa(a,b));d?g.Yb(e,a.C)?(d=a.B,e=a.C):d="_"+S3++:d=b.getAttribute("id")||"_"+S3++;a=v4(b,"t")+c;b=v4(b,"d")||0x8000000000000;if(2==e.Gd||3==e.Gd)c=e.Wf,e.Wf=e.gg,e.gg=c;return new Q3(a,b,0,d,e)},A4=function(a){t4.call(this);
this.o=new Map;this.w=new Map;this.B=new Map;this.u=new Map;this.C=a},xpa=function(a,b,c,d,e){0==d&&(d=0x8000000000000);
var f={},k=b.wpWinPosId;k&&Object.assign(f,a.w.get(k));(k=b.wsWinStyleId)&&Object.assign(f,a.B.get(k));a=b.rcRowCount;void 0!=a&&(f.Wf=a);b=b.ccColCount;void 0!=b&&(f.gg=b);if(2===f.Gd||3===f.Gd)b=f.Wf,f.Wf=f.gg,f.gg=b;return new Q3(c,d,0,e,f)},B4=function(a,b,c,d,e,f,k){V3.call(this,a,b,c,d,e,f,k);
this.type=1},C4=function(a,b,c){this.D=c;
this.version=this.C=this.w=this.o=0;this.u=new DataView(a);this.A=[]},D4=function(a){var b=a.o;
a.o+=1;return a.u.getUint8(b)},E4=function(a){var b=a.o;
a.o+=4;return a.u.getUint32(b)},F4=function(a,b){t4.call(this);
this.u=a;this.track="CC3"==b.A?4:0;this.o=new b4;this.o.A=1<<this.track},zpa=function(a){if("string"===typeof a)return!1;
a=new C4(a,8,0);return ypa(a)},ypa=function(a){if(!(a.o<a.u.byteLength)||1380139777!=E4(a))return!1;
a.version=D4(a);if(1<a.version)return!1;D4(a);D4(a);D4(a);return!0},G4=function(a,b,c,d,e,f,k){V3.call(this,a,b,c,d,e,f,k);
g.L(this.element,"ytp-caption-window-rollup");this.type=2;this.J=[];this.N=this.K=this.ha=0;this.S=NaN;this.Aa=0;this.Ea=null;this.ia=new g.J(this.BL,433,this);g.B(this,this.ia);g.kh(this.element,"overflow","hidden")},Apa=function(a,b){return(a.C?b.offsetHeight:b.offsetWidth)+1},Bpa=function(a){if(isNaN(a.S)){var b=a.w.gg;
if(b){var c=g.Ld("SPAN");g.Vd(c,"\u2013".repeat(b));g.kh(c,W3(a,a.w.wb));a.D.appendChild(c);a.S=c.offsetWidth;a.D.removeChild(c)}else a.S=0}return a.S},Cpa=function(a,b){if(!b)return"";
a.C&&1!=a.B.params.it&&(b*=-1);return"translate"+(a.C?"X":"Y")+"("+b+"px)"},Dpa=function(a){a.J=[].concat(g.fa(document.getElementsByClassName("caption-visual-line")));
for(var b=a.B.params.Wf,c=0,d=0,e=a.J.length-1;c<b&&-1<e;){var f=a.J[e];d+=a.C?f.offsetWidth:f.offsetHeight;c++;e--}a.J.length<b&&(d*=b/a.J.length);a.K=d;a.N=Math.max(Bpa(a),a.Aa,Apa(a,a.D))},Epa=function(a,b){Dpa(a);
var c=a.J.reduce(function(e,f){return(a.C?f.offsetWidth:f.offsetHeight)+e},0);
c=a.K-c;if(c!=a.ha){var d=0<c&&0==a.ha;b||isNaN(c)||d||(g.L(a.element,"ytp-rollup-mode"),g.Xm(a.ia));g.kh(a.D,"transform",Cpa(a,c));a.ha=c}Dpa(a)},H4=function(){t4.call(this)},Fpa=function(a,b,c,d,e,f,k,l,m){switch(k.tagName){case "b":l.bold=!0;
break;case "i":l.te=!0;break;case "u":l.underline=!0}for(var n=0;n<k.childNodes.length;n++){var q=k.childNodes[n];if(3==q.nodeType)q=new P3(b,c,d,e.id,q.nodeValue,f||0<n,g.Wb(l)?void 0:l),m.push(q),R3(e,q);else{var t={};g.Pa(t,l);Fpa(a,b,c,d,e,!0,q,t,m)}}},I4=function(a){var b=a.split(":");
a=0;b=g.p(b);for(var c=b.next();!c.done;c=b.next())a=60*a+parseFloat(c.value);return 1E3*a},Gpa=function(a,b,c,d){d=Object.assign({Ei:0},d);
return new Q3(a,b,c,"_"+S3++,d)},J4=function(a){g.A.call(this);
this.u=a;this.o=null},Ipa=function(a){var b={};
if(a=C3(a))b.lang=a,Hpa.test(a)&&(b.Gd=1);return b},M4=function(a){g.cR.call(this,a);
this.A=a.P();this.T=a.getVideoData();this.ra=g.nL(a);this.S=a;var b=null,c=g.Mn("yt-html5-player-modules::subtitlesModuleData");c&&(b=new g.wn(c));this.ea=b;this.w={wb:{}};this.C={wb:{}};this.J=[];this.U={};this.W={};this.K=!1;this.ia=g.eR(this.T,this.S);this.xa=!!this.T.captionTracks.length;this.ya=!!this.T.wj;this.ba="3"==this.A.controlsType;b=a.app.B;c=!(!b||!b.nl());this.oa=!(!b||!b.Oh());this.B=this.ba&&c&&!this.ia;this.H=!this.B&&this.ba&&this.oa&&this.ia;this.u=this.D=this.G=this.V=this.sa=
null;this.da=new J4(this.A);g.B(this,this.da);c=b=this.o=null;this.B||(b=new g.Um(this.bB,void 0,this),g.B(this,b),c=new g.J(this.gN,2E3,this),g.B(this,c));this.aa=b;this.ha=c;this.N=new g.P(this);g.B(this,this.N);this.B||this.N.M(a,"resize",this.wt);this.N.M(a,"onPlaybackAudioChange",this.gJ);this.N.M(a,g.vE("captions"),this.HF,this);this.N.M(a,"crx_captions",this.IF,this);K4(this,L4(this,"display-settings")||{})},N4=function(a){if(1==a.A.fg||1==a.T.fg||"alwayson"==g.YC(a.T,"yt:cc"))return!0;
if(2==a.A.fg){var b=L4(a,"module-enabled");if(null!=b)return!!b}if(a.T.captionTracks.length)var c=a.player.getAudioTrack().mp;return"ON"==c||"on"==g.YC(a.T,"yt:cc")},O4=function(a,b){if(a.o&&(void 0===b||!b)||!a.T.captionTracks.length)return!1;
var c=a.player.getAudioTrack();return!!c.qm||"FORCED_ON"==c.mp},Q4=function(a,b){if(a.u){if(a.D&&a.D.o)return a.D.o;
var c=b;c||(c=a.ya?!1:a.xa?!1:!0);c=D3(a.u.u,c);for(var d=[a.T.captionsLanguagePreference,a.A.captionsLanguagePreference,g.YC(a.T,"yt:cc_default_lang")],e=0;e<d.length;e++)for(var f=0;f<c.length;f++)if(C3(c[f])==d[e])return c[f];return a.D&&a.D.Ap?a.D.Ap:(d=c.find(function(k){return k.isDefault}))?d:c[0]||P4(a)}return null},P4=function(a){return a.D&&a.D.qm},R4=function(a){var b=P4(a);
return!!b&&a.o==b},Jpa=function(a,b){for(var c=a.S.app.B.Za().textTracks,d=a.o.toString(),e=0;e<c.length;e++){var f=c[e];
f.id==d&&(b?"showing"!=f.mode&&(f.mode="showing"):"showing"==f.mode&&(f.mode="disabled"))}},T4=function(a,b,c){a.loaded&&a.unload();
null!=c&&(a.K=c,a.K&&S4(a,"module-enabled",!!b));a.o=b;O4(a)&&(a.o=P4(a));a.load()},Kpa=function(a,b){var c=a.ra.getVideoContentRect(!0).height;
if(!c)return null;var d=a.ra.getPlayerSize();switch(null!=b.params.Ei?b.params.Ei:1<b.o.length?1:0){case 1:return new B4(b,a.w,a.C,c,d.width,d.height,a.A.experiments);case 2:return new G4(b,a.w,a.C,c,d.width,d.height,a.A.experiments);default:return new V3(b,a.w,a.C,c,d.width,d.height,a.A.experiments)}},K4=function(a,b,c){var d=U4.wb;
a.w={};g.Pa(a.w,U4);a.w.wb={};g.Pa(a.w.wb,d);a.C={wb:{}};var e=b.backgroundOverride?a.C:a.w,f=b.background||d.background;y4.test(f);e.wb.background=f;e=b.colorOverride?a.C:a.w;f=b.color||d.color;y4.test(f);e.wb.color=f;e=b.windowColorOverride?a.C:a.w;f=b.windowColor||U4.windowColor;y4.test(f);e.windowColor=f;e=b.backgroundOpacityOverride?a.C:a.w;f=b.backgroundOpacity;null==f&&(f=d.backgroundOpacity);e.wb.backgroundOpacity=f;e=b.fontSizeIncrementOverride?a.C:a.w;f=b.fontSizeIncrement;null==f&&(f=d.fontSizeIncrement);
e.wb.fontSizeIncrement=f;f=b.fontStyleOverride?a.C:a.w;e=b.fontStyle;null==e&&(e=d.bold&&d.te?3:d.bold?1:d.te?2:0);f=f.wb;switch(e){case 1:f.bold=!0;delete f.te;break;case 2:delete f.bold;f.te=!0;break;case 3:f.bold=!0;f.te=!0;break;default:delete f.bold,delete f.te}e=b.textOpacityOverride?a.C:a.w;f=b.textOpacity;null==f&&(f=d.textOpacity);e.wb.textOpacity=f;e=b.windowOpacityOverride?a.C:a.w;f=b.windowOpacity;null==f&&(f=U4.windowOpacity);e.windowOpacity=f;e=b.charEdgeStyleOverride?a.C:a.w;f=b.charEdgeStyle;
null==f&&(f=d.charEdgeStyle);e.wb.charEdgeStyle=f;e=b.fontFamilyOverride?a.C:a.w;f=b.fontFamily;null==f&&(f=d.fontFamily);e.wb.fontFamily=f;a.loaded&&a.wt();c&&S4(a,"display-settings",b)},Mpa=function(a,b){if(b&&!a.G){var c=T3({Gd:0,
lang:"en"});a.G=[c,new P3(c.start,c.end-c.start,0,c.id,"Captions look like this")];g.BL(a.player,a.G)}else!b&&a.G&&(Lpa(a,a.G),a.G=null)},Lpa=function(a,b){g.XU(a.player.app,b,void 0);
(0,g.y)(b,function(c){g.bb(this.J,c)},a);
a.aa.ki()},L4=function(a,b){if(!a.ea)return null;
try{var c=a.ea.get(b)}catch(d){a.ea.remove(b)}return c},S4=function(a,b,c){if(a.ea)try{a.ea.set(b,c)}catch(d){}};
g.$z.prototype.dr=g.da(11,function(a){return a?this.toString()==a.toString():!1});
g.av.prototype.Fm=g.da(10,function(a){return(a=this.mg(a))?a.o:0});
g.tz.prototype.Fm=g.da(9,function(){return 0});
g.Ht.prototype.xj=g.da(8,function(){for(var a=g.xd(document,"track",void 0,this.o),b=0;b<a.length;b++)g.Qd(a[b])});
g.US.prototype.xj=g.da(7,function(){this.o.xj()});
g.Ht.prototype.nl=g.da(6,function(){return!!this.o.textTracks});
g.US.prototype.nl=g.da(5,function(){return this.o.nl()});
g.Ht.prototype.sj=g.da(4,function(a){for(var b=0;b<a.length;b++)this.o.appendChild(a[b])});
g.US.prototype.sj=g.da(3,function(a){this.o.sj(a)});
g.xt.prototype.Oh=g.da(2,function(){});
g.Ht.prototype.Oh=g.da(1,function(){return!(!this.o.textTracks||!this.o.textTracks.addEventListener)});
g.US.prototype.Oh=g.da(0,function(){return this.o.Oh()});
var Hpa=/^(ar|ckb|dv|he|iw|fa|nqo|ps|sd|ug|ur|yi|.*[-_](Adlm|Arab|Hebr|Nkoo|Rohg|Thaa))(?!.*[-_](Latn|Cyrl)($|-|_))($|-|_)/i,y4=/^#(?:[0-9a-f]{3}){1,2}$/i;g.r(F3,g.A);F3.prototype.Gz=function(){return!1};
F3.prototype.Z=function(){this.Og();g.A.prototype.Z.call(this)};
g.r(G3,F3);G3.prototype.Rq=function(a,b,c){b=this.Pj(a,b);var d=(0,g.x)(function(e){this.o=null;c(e.responseText,a)},this);
this.Og();this.o=g.sp(b,{format:"RAW",onSuccess:d,withCredentials:!0})};
G3.prototype.Sq=function(a){if(this.A)for(var b=g.p(this.A.captionTracks),c=b.next();!c.done;c=b.next())E3(this.u,c.value);a()};
G3.prototype.Pj=function(a,b){var c=a.G,d={fmt:b};if("srv3"==b||"3"==b)g.Cp()?Object.assign(d,{xorb:2,xobt:1,xovt:1}):Object.assign(d,{xorb:2,xobt:3,xovt:3});a.o&&(d.tlang=C3(a));return g.ap(c,d)};
G3.prototype.Og=function(){this.o&&this.o.abort()};
H3.prototype.contains=function(a){a=g.lb(this.o,a);return 0<=a||0>a&&1==(-a-1)%2};
H3.prototype.length=function(){return this.o.length/2};
g.r(I3,g.A);g.h=I3.prototype;g.h.Z=function(){g.A.prototype.Z.call(this);this.u&&this.u.cancel()};
g.h.Mx=function(){J3(this,this.A.getCurrentTime())};
g.h.reset=function(){this.B=new H3;this.u&&(this.u.cancel(),this.u=null)};
g.h.Vw=function(){var a;if(a=null!==this.o)a=this.o,a=a.o.Rf(a);!a||this.u||this.o&&30<this.o.startTime-this.A.getCurrentTime()||(a=this.o,a=a.o.Gi(a),a.o[0].duration?(this.B.contains(a.o[0].u)||K3(this,a),this.o=g.Ta(a.o)):!g.T(this.U.experiments,"force_caption_seek_for_live_killswitch")&&this.o&&this.o.B&&this.o.B+this.A.vb()<this.A.getCurrentTime()&&J3(this,this.A.getCurrentTime()));this.G.start()};
g.h.wL=function(a){var b=!(this.C?a.response:a.responseText)||400<=a.status,c=g.yz(a);c?(a=g.bz(this.w,this.J,{}),b=this.w,g.Yy(b.u,a,c),b.requestId=a.get("req_id"),K3(this,this.w)):(b||null===this.D||(c=this.w.o[0],this.C?this.D(a.response,1E3*(c.startTime+this.A.vb())):this.D(a.responseText,1E3*(c.startTime+this.A.vb()))),this.u=this.w=null)};
g.r(L3,F3);g.h=L3.prototype;g.h.Rq=function(a,b,c){this.Og();b=kpa(this,a.getId());b||(b=a.u,b=this.o.u?N3(this,b,"386"):N3(this,b));if(b){var d=1E3*(b.index.Fm(b.index.re())-b.index.Qc(b.index.re()));this.A=new I3(new g.Ty,this.D,b,function(e,f){c(e,a,f,d)},this.C||g.Js(b.info),(0,g.x)(function(){this.A&&this.A.reset();
this.w=!0},this))}};
g.h.Gz=function(){var a=this.w;this.w=!1;return a};
g.h.Sq=function(a){var b;this.C?b=[new g.$z({id:"rawcc",languageCode:"rawcc",languageName:"CC1",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"}),new g.$z({id:"rawcc",languageCode:"rawcc",languageName:"CC3",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"})]:b=this.o.u?M3(this,"386"):M3(this);b=g.p(b);for(var c=b.next();!c.done;c=b.next())E3(this.u,c.value);a()};
g.h.Og=function(){this.A&&(this.A.dispose(),this.A=null)};
g.h.Pj=function(){return""};
g.r(O3,F3);O3.prototype.Rq=function(a,b,c){b=this.Pj(a,b);var d=(0,g.x)(function(e){this.o=null;c(e.responseText,a)},this);
this.Og();this.o=g.sp(b,{format:"RAW",onSuccess:d,withCredentials:!0})};
O3.prototype.Sq=function(a){var b=this.w,c={type:"list",tlangs:1,v:this.A,vssids:1};this.C&&(c.asrs=1);b=g.ap(b,c);c=(0,g.x)(function(d){this.o=null;if((d=d.responseXML)&&d.firstChild){for(var e=g.p(d.getElementsByTagName("track")),f=e.next();!f.done;f=e.next()){var k=f.value;f=k.getAttribute("lang_code");var l=k.getAttribute("lang_translated"),m=k.getAttribute("name"),n=k.getAttribute("kind"),q=k.getAttribute("id"),t="true"==k.getAttribute("lang_default"),u="true"==k.getAttribute("cantran");k=k.getAttribute("vss_id");
E3(this.u,new g.$z({languageCode:f,languageName:l,name:m,kind:n,id:q,is_servable:!0,is_translateable:u,vss_id:k,is_default:t}))}d=d.getElementsByTagName("target");e=d.length;for(f=0;f<e;f++)l=d[f].getAttribute("lang_code"),m=d[f].getAttribute("lang_translated"),n=d[f].getAttribute("lang_original"),q=d[f].getAttribute("id"),t="true"==d[f].getAttribute("lang_default"),l={languageCode:l,languageName:m,languageOriginal:n,id:q,isDefault:t},this.D[l.languageCode]=l.languageName,this.B.push(l)}a()},this);
this.Og();this.o=g.sp(b,{format:"RAW",onSuccess:c,withCredentials:!0})};
O3.prototype.Pj=function(a,b){var c=this.w,d={v:this.A,type:"track",lang:a.u,name:a.getName(),kind:a.w,fmt:b};a.o&&(d.tlang=C3(a));return c=g.ap(c,d)};
O3.prototype.Og=function(){this.o&&this.o.abort()};var lpa=["left","right","center","justify"];var U4={windowColor:"#080808",windowOpacity:0,textAlign:2,uf:7,ue:50,Xf:100,wb:{background:"#080808",backgroundOpacity:.75,charEdgeStyle:0,color:"#fff",fontFamily:4,fontSizeIncrement:0,textOpacity:1,offset:1}};g.r(P3,g.sE);P3.prototype.toString=function(){return g.sE.prototype.toString.call(this)};g.r(Q3,g.sE);Q3.prototype.toString=function(){return g.sE.prototype.toString.call(this)};
var S3=0;g.r(V3,g.S);g.h=V3.prototype;g.h.JG=function(a,b){var c=g.Bh(this.element,this.element.parentElement);this.ra=a-c.x;this.xa=b-c.y;g.L(this.element,"ytp-dragging")};
g.h.IG=function(a,b){var c=g.Eh(this.element),d=a-this.ra-.02*this.Na,e=b-this.xa-.02*this.Ma,f=(d+c.width/2)/this.ba*3;f=Math.floor(g.kd(f,0,2));var k=(e+c.height/2)/this.ya*3;k=Math.floor(g.kd(k,0,2));var l=f+3*k;d=(d+f/2*c.width)/this.ba;d=100*g.kd(d,0,1);c=(e+k/2*c.height)/this.ya;c=100*g.kd(c,0,1);this.B.params.uf=l;this.B.params.Xf=c;this.B.params.ue=d;this.w.uf=l;this.w.Xf=c;this.w.ue=d;this.gA()};
g.h.HG=function(){g.hn(this.element,"ytp-dragging")};
g.h.gA=function(){this.Lh(this.G)};
g.h.Lh=function(a){var b=Math.min(this.Nv(),this.ba),c=this.Mv(),d="";3==this.B.params.Gd&&(d="rotate(180deg)");g.kh(this.element,{top:0,left:0,right:"",bottom:"",width:b?b+"px":"",height:c?c+"px":"","max-width":"96%","max-height":"96%",margin:"",transform:""});this.bp(a);a={transform:d,top:"",left:"",width:b?b+"px":"",height:c?c+"px":"","max-width":"","max-height":""};var e=.96*this.w.ue+2;d=this.w.uf;switch(d){case 0:case 3:case 6:a.left=e+"%";break;case 1:case 4:case 7:a.left=e+"%";e=this.D.offsetWidth;
b||e?(b=b||e+1,a.width=b+"px",a["margin-left"]=b/-2+"px"):a.transform+=" translateX(-50%)";break;case 2:case 5:case 8:a.right=100-e+"%"}b=.96*this.w.Xf+2;switch(d){case 0:case 1:case 2:a.top=b+"%";break;case 3:case 4:case 5:a.top=b+"%";(c=c||this.element.clientHeight)?(a.height=c+"px",a["margin-top"]=c/-2+"px"):a.transform+=" translateY(-50%)";break;case 6:case 7:case 8:a.bottom=100-b+"%"}g.kh(this.element,a)};
g.h.bp=function(a){var b;for(b=0;b<a.length&&a[b]==this.G[b];b++);if(this.V||this.G.length>b)b=0,this.V=!1,this.G=[],this.H=this.da=this.W=null,g.Od(this.D);for(;b<a.length;b++)Z3(this,a[b])};
g.h.Nv=function(){return 0};
g.h.Mv=function(){return 0};
g.h.toString=function(){return g.S.prototype.toString.call(this)};$3.prototype.B=function(){};b4.prototype.clear=function(){this.w=this.u=this.mode=0;this.o=[];this.reset()};
b4.prototype.reset=function(){this.mode=0;this.B.reset(0);this.C.reset(1)};
var c4=[128,1,2,131,4,133,134,7,8,137,138,11,140,13,14,143,16,145,146,19,148,21,22,151,152,25,26,155,28,157,158,31,32,161,162,35,164,37,38,167,168,41,42,171,44,173,174,47,176,49,50,179,52,181,182,55,56,185,186,59,188,61,62,191,64,193,194,67,196,69,70,199,200,73,74,203,76,205,206,79,208,81,82,211,84,213,214,87,88,217,218,91,220,93,94,223,224,97,98,227,100,229,230,103,104,233,234,107,236,109,110,239,112,241,242,115,244,117,118,247,248,121,122,251,124,253,254,127,0,129,130,3,132,5,6,135,136,9,10,139,
12,141,142,15,144,17,18,147,20,149,150,23,24,153,154,27,156,29,30,159,160,33,34,163,36,165,166,39,40,169,170,43,172,45,46,175,48,177,178,51,180,53,54,183,184,57,58,187,60,189,190,63,192,65,66,195,68,197,198,71,72,201,202,75,204,77,78,207,80,209,210,83,212,85,86,215,216,89,90,219,92,221,222,95,96,225,226,99,228,101,102,231,232,105,106,235,108,237,238,111,240,113,114,243,116,245,246,119,120,249,250,123,252,125,126,255];e4.prototype.set=function(a){this.o=a};
e4.prototype.get=function(){return this.o};
f4.prototype.clear=function(){this.o=0};
f4.prototype.update=function(){this.o=2==this.o?1:0};
f4.prototype.matches=function(a,b){return 0!=this.o&&a==this.A&&b==this.u};
g4.prototype.jg=function(a){this.Zd=a.Zd;this.timestamp=a.timestamp};
g4.prototype.reset=function(){this.timestamp=this.Zd=0};
h4.prototype.updateTime=function(a){for(var b=1;15>=b;++b)for(var c=1;32>=c;++c)this.A[b][c].timestamp=a};
h4.prototype.debugString=function(){for(var a="\n",b=1;15>=b;++b){for(var c=1;32>=c;++c){var d=this.A[b][c];a=0==d.Zd?a+"_":a+String.fromCharCode(d.Zd)}a+="\n"}return a};
h4.prototype.reset=function(a){for(var b=0;15>=b;b++)for(var c=0;32>=c;c++)this.A[b][c].reset();this.w=a;this.o=0;this.u=this.row=1};
var ppa=[32,33,34,35,36,37,38,39,40,41,225,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,233,93,237,243,250,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,231,247,209,241,9632],qpa=[174,176,189,191,8482,162,163,9834,224,32,232,226,234,238,244,251],rpa=[193,201,211,218,220,252,8216,161,42,39,9473,169,8480,183,8220,8221,192,194,199,200,202,203,235,
206,207,239,212,217,249,219,171,187],spa=[195,227,205,204,236,210,242,213,245,123,125,92,94,95,124,126,196,228,214,246,223,165,164,9475,197,229,216,248,9487,9491,9495,9499];o4.prototype.reset=function(a,b){this.B=b;this.style.set(2);this.u=this.C;this.A=this.D;this.o=this.u;var c=(a<<2)+(b<<1);this.C.reset(c);this.D.reset(c);this.G.reset((a<<2)+(b<<1)+1)};
a4.prototype.reset=function(a){this.B=a;this.o.clear();this.w=this.A;this.A.reset(a,0);this.C.reset(a,1)};g.r(t4,g.A);t4.prototype.reset=function(){};g.r(u4,t4);u4.prototype.reset=function(){this.G={};this.u=this.o=null;this.D=!0};
u4.prototype.A=function(a,b){var c=a.firstChild;c.getAttribute("format");b=b||0;Number.isFinite(b);c=Array.from(c.childNodes);c=g.p(c);for(var d=c.next();!d.done;d=c.next())if(d=d.value,1==d.nodeType)switch(d.tagName){case "head":var e=d;break;case "body":var f=d}if(e)for(e=Array.from(e.childNodes),e=g.p(e),c=e.next();!c.done;c=e.next())if(c=c.value,1==c.nodeType)switch(c.tagName){case "pen":d=c.getAttribute("id");var k=this.w,l={},m=c.getAttribute("p");m&&g.Pa(l,this.w[m]);m=w4(c,"b");null!=m&&(l.bold=
m);m=w4(c,"i");null!=m&&(l.te=m);m=w4(c,"u");null!=m&&(l.underline=m);m=x4(c,"et");null!=m&&(l.charEdgeStyle=m);m=x4(c,"of");null!=m&&(l.offset=m);m=z4(c,"bc");null!=m&&(l.background=m);m=z4(c,"ec");null!=m&&(l.qp=m);m=z4(c,"fc");null!=m&&(l.color=m);m=x4(c,"fs");null!=m&&0!=m&&(l.fontFamily=m);m=v4(c,"sz");void 0!=m&&(l.fontSizeIncrement=m/100-1);m=v4(c,"bo");void 0!=m&&(l.backgroundOpacity=m/255);m=v4(c,"fo");void 0!=m&&(l.textOpacity=m/255);m=x4(c,"rb");null!=m&&10!=m&&0!=m&&(l.hd=10<m?m-1:m);
m=x4(c,"hg");null!=m&&(l.yE=m);c=x4(c,"te");null!=c&&(2==c&&(l.bold=!1,c=1),l.Be=c);k[d]=l;break;case "ws":d=c.getAttribute("id");this.J[d]=upa(this,c);break;case "wp":d=c.getAttribute("id"),this.H[d]=vpa(this,c)}if(f){e=b;c=[];f=Array.from(f.childNodes);f=g.p(f);for(d=f.next();!d.done;d=f.next())if(d=d.value,1==d.nodeType)switch(d.tagName){case "w":this.o=wpa(this,d,e,!1);g.B(this,this.o);(d=this.G[this.o.id])&&d.end>this.o.start&&(d.end=this.o.start);this.G[this.o.id]=this.o;c.push(this.o);break;
case "p":var n=e;k=[];l=d.getAttribute("w")||this.B;m=!!w4(d,"a");n=(v4(d,"t")||0)+n;var q=v4(d,"d")||5E3;m||(!this.D&&this.u&&this.u.windowId==l&&this.u.end>n&&(this.u.end=n),this.u&&"\n"==this.u.text&&(this.u.text=""));var t=m?6:5,u=this.w[d.getAttribute("p")],z=[].concat(g.fa(d.childNodes));z.length&&(this.D=null!=d.getAttribute("d"));for(var C=0;C<z.length;C++){var D=z[C],H=void 0;0<C&&(m=!0);var K=void 0;1==D.nodeType&&(K=D);if(K&&"s"==K.tagName){if((D=this.w[K.getAttribute("p")])&&D.hd&&(1==
D.hd?(D=z.slice(C,C+4),4==D.length&&(H=s4(n,q,l,m,t,D,this.w),C+=3)):H=s4(n,q,l,m,t,[K],this.w)),!H){var E=K;H=n;K=q;D=l;var N=m,ba=t,Ca=E.textContent?E.textContent:"",Ka=this.w[E.getAttribute("p")];E=v4(E,"t")||0;H=new P3(H+E,K-E,ba,D,Ca,N,Ka)}}else H=new P3(n,q,t,l,D.textContent||"",m,u);k.push(H);this.u=H}if(0<k.length)for(k[0].windowId==this.B&&(this.o=wpa(this,d,e,!0),g.B(this,this.o),c.push(this.o)),d=g.p(k),k=d.next();!k.done;k=d.next())k=k.value,k.windowId=this.o.id,R3(this.o,k),c.push(k)}e=
c}else e=[];return e};var V4=new Map([[4095,"#fff"],[4080,"#ff0"],[240,"#0f0"],[255,"#0ff"],[15,"#00f"],[3855,"#f0f"],[3840,"#f00"],[526344,"#080808"]]);g.r(A4,t4);A4.prototype.reset=function(){this.u.clear()};
A4.prototype.A=function(a,b){var c=JSON.parse(a);if(!c)return[];if(c.pens)for(var d=0,e=g.p(c.pens),f=e.next();!f.done;f=e.next()){f=f.value;var k={},l=f.pParentId;l&&Object.assign(k,this.o.get(l));f.bAttr&&(k.bold=!0);f.iAttr&&(k.te=!0);f.uAttr&&(k.underline=!0);l=f.ofOffset;null!=l&&(k.offset=l);f.szPenSize&&(k.fontSizeIncrement=f.szPenSize/100-1);l=f.etEdgeType;null!=l&&(k.charEdgeStyle=l);f.ecEdgeColor&&(k.qp=V4.get(f.ecEdgeColor)||"#fff");l=f.fsFontStyle;null!=l&&0!==l&&(k.fontFamily=l);f.fcForeColor&&
(k.color=V4.get(f.fcForeColor)||"#fff");f.foForeAlpha&&(k.textOpacity=f.foForeAlpha/255);f.bcBackColor&&(k.background=V4.get(f.bcBackColor)||"#fff");f.boBackAlpha&&(k.backgroundOpacity=f.boBackAlpha/255);this.o.set(d++,k)}if(c.wsWinStyles)for(d=0,e=g.p(c.wsWinStyles),f=e.next();!f.done;f=e.next())f=f.value,k={},(l=f.wsParentId)?Object.assign(k,this.B.get(l)):Object.assign(k,this.C),void 0!=f.mhModeHint&&(k.Ei=f.mhModeHint),void 0!=f.juJustifCode&&(k.textAlign=f.juJustifCode),void 0!=f.pdPrintDir&&
(k.Gd=f.pdPrintDir),void 0!=f.sdScrollDir&&(k.it=f.sdScrollDir),void 0!=f.wfcWinFillColor&&(k.windowColor=V4.get(f.wfcWinFillColor)||"#fff"),void 0!=f.wfoWinFillAlpha&&(k.windowOpacity=f.wfoWinFillAlpha/255),this.B.set(d++,k);if(c.wpWinPositions)for(d=0,e=g.p(c.wpWinPositions),f=e.next();!f.done;f=e.next())f=f.value,k={},(l=f.wpParentId)&&Object.assign(k,this.w.get(l)),l=k,void 0!=f.ahHorPos&&(l.ue=f.ahHorPos),void 0!=f.apPoint&&(l.uf=f.apPoint),void 0!=f.avVerPos&&(l.Xf=f.avVerPos),void 0!=f.ccCols&&
(l.gg=f.ccCols),void 0!=f.rcRows&&(l.Wf=f.rcRows),this.w.set(d++,k);if(c.events){d=[];c=g.p(c.events);for(e=c.next();!e.done;e=c.next()){var m=e.value;e=(m.tStartMs||0)+b;f=m.dDurationMs||0;if(m.id)k=String(m.id),e=xpa(this,m,e,f,k),d.push(e),this.u.set(k,e);else{m.wWinId?k=m.wWinId.toString():(k="_"+S3++,l=xpa(this,m,e,f,k),d.push(l),this.u.set(k,l));0===f&&(f=5E3);k=this.u.get(k);var n=!!m.aAppend;l=n?6:5;var q=m.segs,t=null;m.pPenId&&(t=this.o.get(m.pPenId));m=g.p(q);for(q=m.next();!q.done;q=m.next()){q=
q.value;var u=q.utf8;if(u){var z=q.tOffsetMs||0,C=null;q.pPenId&&(C=this.o.get(q.pPenId));if(2===(null!=k.params.Ei?k.params.Ei:1<k.o.length?1:0)&&n&&"\n"===u)continue;n=new P3(e+z,f-z,l,k.id,u,n,C||t);d.push(n);R3(k,n)}n=!0}}}c=d}else c=[];return c};g.r(B4,V3);B4.prototype.bp=function(a){var b=this.B.o;V3.prototype.bp.call(this,a);for(a=a.length;a<b.length;a++){var c=b[a];if(f&&c.o==e)var d=f;else{d={};g.Pa(d,c.o);g.Pa(d,Npa);var e=c.o;var f=d}Z3(this,c,d)}};
var Npa={wE:!0};g.r(C4,$3);C4.prototype.B=function(a,b,c,d,e){if(c<d){var f="_"+S3++;c=c/1E3-this.D;d=d/1E3-this.D;a=new Q3(c,d-c,5,f,{textAlign:0,uf:0,ue:2.5*b,Xf:5.33*a});e=new P3(c,d-c,5,f,e);this.A.push(a);this.A.push(e)}};
g.r(F4,t4);F4.prototype.A=function(a){a=new C4(a,a.byteLength,this.u);if(ypa(a)){for(;a.o<a.u.byteLength;)for(0==a.version?a.w=E4(a)*(1E3/45):1==a.version&&(a.w=4294967296*E4(a)+E4(a)),a.C=D4(a);0<a.C;a.C--){var b=D4(a),c=D4(a),d=D4(a);b&4&&(b&3)==this.track&&(0==this.track||1==this.track)&&(b=this.o,b.o.push({time:a.w,type:this.track,Ou:c,Pu:d,order:b.o.length}))}opa(this.o,a);return a.A}return[]};
F4.prototype.reset=function(){this.o.clear()};g.r(G4,V3);g.h=G4.prototype;g.h.gA=function(){g.Ym(this.ia)};
g.h.BL=function(){g.hn(this.element,"ytp-rollup-mode");this.Lh(this.Ea,!0)};
g.h.Mv=function(){return this.C?this.N:this.K};
g.h.Nv=function(){return this.C?this.K:this.N};
g.h.Lh=function(a,b){this.Ea=a;if(this.B.params.Wf){for(var c=0,d=0;d<this.G.length&&c<a.length;d++)this.G[d]==a[c]&&c++;0<c&&c<a.length&&(a=this.G.concat(a.slice(c)));this.Aa=this.N;this.K=this.N=0;V3.prototype.Lh.call(this,a);Epa(this,b);V3.prototype.Lh.call(this,a)}else V3.prototype.Lh.call(this,a)};g.r(H4,t4);
H4.prototype.A=function(a,b){for(var c=[],d=a.split(Opa),e=1;e<d.length;e++){var f=d[e],k=b;if(""!=f&&!Ppa.test(f)){var l=W4.exec(f);if(l&&4<=l.length){var m=I4(l[1]),n=I4(l[2])-m;m+=k;var q,t=q=void 0,u=void 0,z=void 0,C=(l=l[3])?l.split(" "):[];l={textAlign:2};C=g.p(C);for(var D=C.next();!D.done;D=C.next())if(D=D.value.split(":"),2==D.length){var H=D[1];switch(D[0]){case "line":D=H.split(",");D[0].endsWith("%")&&(z=D[0],l.Xf=Number.parseInt(z,10),2==D.length&&(u=D[1].trim()));break;case "position":D=H.split(",");
t=D[0];l.ue=Number.parseInt(t,10);2==D.length&&(q=D[1].trim());break;case "align":switch(H){case "start":l.textAlign=0;break;case "middle":l.textAlign=2;break;case "end":l.textAlign=1}}}z||(l.Xf=100,u||(u="end"));if(!t)switch(l.textAlign){case 0:l.ue=0;break;case 1:l.ue=100;break;default:l.ue=50}t=0;switch(u){case "center":t+=3;break;case "end":t+=6;break;default:t+=0}switch(q){case "line-left":t+=0;break;case "center":t+=1;break;case "line-right":t+=2;break;default:switch(l.textAlign){case 0:t+=
0;break;case 2:t+=1;break;case 1:t+=2}}l.uf=0>t||8<t?7:t;q=l;f=f.substring(W4.lastIndex).replace(/[\x01-\x09\x0b-\x1f]/g,"");t=q;q=f;f={};if(0>q.indexOf("<")&&0>q.indexOf("&"))k=Gpa(m,n,5,t),n=new P3(m,n,5,k.id,q,!1,g.Wb(f)?void 0:f),c.push(k),c.push(n),R3(k,n);else for(u=q.split(Qpa),1==u.length?(q=5,t=Gpa(m,n,q,t)):(z=q=6,t=Object.assign({gg:32},t),t=new Q3(m,n,z,"_"+S3++,t)),c.push(t),z=m,l=0;l<u.length;l++)C=u[l],0==l%2?(D=g.x0("<html>"+C+"</html>"),D.getElementsByTagName("parsererror").length?
(H=D.createElement("span"),H.appendChild(D.createTextNode(C))):H=D.firstChild,Fpa(this,z,n-(z-m),q,t,0<l,H,f,c)):z=I4(C)+k}W4.lastIndex=0}}return c};
var Ppa=/^NOTE/,Opa=/(?:\r\n|\r|\n){2,}/,W4=RegExp("^((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})[\\t ]+--\x3e[\\t ]+((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})(?:[\\t ]*)(.*)(?:\\r\\n|\\r|\\n)","gm"),Qpa=/<((?:[\d]{2}:)?[\d]{2}:[\d]{2}\.[\d]{3})>/;g.r(J4,g.A);J4.prototype.clear=function(){this.o&&this.o.dispose();this.o=null};
J4.prototype.reset=function(){this.o&&this.o.reset()};
J4.prototype.Z=function(){this.clear();g.A.prototype.Z.call(this)};g.r(M4,g.cR);g.h=M4.prototype;g.h.Z=function(){if(this.B||this.H){var a=this.S.app.B;a&&a.xj()}else Mpa(this,!1);g.cR.prototype.Z.call(this)};
g.h.load=function(){g.cR.prototype.load.call(this);var a=!g.T(this.A.experiments,"web_player_captions_track_list_changed_killswitch");this.D=this.player.getAudioTrack();if(this.u){if(this.o){this.da.clear();if(this.B)Jpa(this,!0);else if(3!=this.player.getPresentingPlayerType()){var b=g.T(this.A.experiments,"html5_enable_json_subtitle")?"json3":"srv3";this.u.Rq(this.o,b,(0,g.x)(this.kM,this))}!a||this.B||this.H||R4(this)||this.player.ma("captionschanged",B3(this.o))}a||(this.o&&!R4(this)?this.player.ma("captionschanged",
B3(this.o)):this.player.ma("onCaptionsTrackListChanged"))}else this.ia?b=new L3(this.T.la,this.player):this.xa?b=new G3(this.A,this.T,this.player.getAudioTrack()):b=new O3(this.T.wj,this.T.videoId,this.T.captionsLanguagePreference||this.A.captionsLanguagePreference||g.YC(this.T,"yt:cc_default_lang")||this.A.Ub,this.T.kp,this.A),this.u=b,g.B(this,this.u),b.Sq((0,g.x)(this.jM,this))};
g.h.unload=function(){this.B&&this.o?Jpa(this,!1):(this.ha&&g.Zm(this.ha),g.xS(this.player.app,"captions",void 0),this.J=[],this.u&&this.u.Og(),this.da.clear(),this.G&&g.BL(this.player,this.G),this.wt());g.cR.prototype.unload.call(this);var a=g.R(this.player.app);a&&g.jJ(a.B);this.player.ma("captionschanged",{})};
g.h.create=function(){(this.ba?this.B||this.H:O4(this)||N4(this))&&this.load()};
g.h.jM=function(){var a;this.K||N4(this)?a=Q4(this,this.K):O4(this)&&(a=P4(this));if(this.B||this.H){for(var b=D3(this.u.u,!0),c=[],d=0;d<b.length;d++){var e=b[d],f={kind:"subtitles",label:g.aA(e),srclang:C3(e),id:e.toString()};this.H||(f.src=this.u.Pj(e,"vtt"));e==a&&(f["default"]=1);c.push(g.Kd("TRACK",f))}a=this.S.app.B;a.sj(c);c=a.Za();this.oa&&this.N.M(c.textTracks,"change",this.lM)}else!this.o&&a&&T4(this,a),this.player.ma("onCaptionsTrackListChanged"),this.player.ma("onApiChange")};
g.h.lM=function(){for(var a=this.S.app.B.Za().textTracks,b=null,c=0;c<a.length;c++)if("showing"==a[c].mode)a:{b=a[c].id;var d=D3(this.u.u,!0);for(var e=0;e<d.length;e++)if(d[e].toString()==b){b=d[e];break a}b=null}(this.loaded?this.o:null)!=b&&T4(this,b,!0)};
g.h.TN=function(){!this.o&&this.B||this.unload()};
g.h.kM=function(a,b,c,d){if(a){this.u.Gz()&&(this.J=[],g.xS(this.S.app,"captions",void 0),this.aa.ki(),this.da.reset());var e=this.da;c=c||0;d=d||0;if("string"!==typeof a){var f=new DataView(a);if(8<=f.byteLength&&1718909296==f.getUint32(4)&&(f=g.Av(f,0,1835295092),a=a.slice(f.dataOffset,f.dataOffset+f.size),!zpa(a))){a=new Uint8Array(a);f=[];for(var k=0,l=0;k<a.length;){var m=a[k++];if(128>m)f[l++]=String.fromCharCode(m);else if(191<m&&224>m){var n=a[k++];f[l++]=String.fromCharCode((m&31)<<6|n&63)}else if(239<
m&&365>m){n=a[k++];var q=a[k++],t=a[k++];m=((m&7)<<18|(n&63)<<12|(q&63)<<6|t&63)-65536;f[l++]=String.fromCharCode(55296+(m>>10));f[l++]=String.fromCharCode(56320+(m&1023))}else n=a[k++],q=a[k++],f[l++]=String.fromCharCode((m&15)<<12|(n&63)<<6|q&63)}a=f.join("")}}if(a)try{if("string"!==typeof a){var u=a,z=d;if(!zpa(u))throw Error("Invalid binary caption track data");e.o||(e.o=new F4(z,b));var C=e.o.A(u,c)}else{if("WEBVTT"==a.substring(0,6))b=a,e.o||(e.o=new H4),z=e.o.A(b,c),.01>Math.random()&&g.no(Error("Deprecated subtitles format in web player: WebVTT")),
u=z;else b:{z=a;if(g.T(e.u.experiments,"html5_enable_json_subtitle"))try{e.o||(e.o=new A4(Ipa(b)));u=e.o.A(z,c);break b}catch(Ca){g.O(Ca);u=[];break b}var D=g.x0(z);if(!D||!D.firstChild){var H=Error("Invalid caption track data");H.params=z;throw H;}if("timedtext"==D.firstChild.tagName){if(3==parseInt(D.firstChild.getAttribute("format"),10)){e.o||(e.o=new u4(Ipa(b),e.u));u=e.o.A(D,c);break b}var K=Error("Unsupported subtitles format in web player (Format2)");K.params=z;throw K;}if("transcript"==D.firstChild.tagName){var E=
Error("Unsupported subtitles format in web player (Format1)");E.params=z;throw E;}var N=Error("Invalid caption track data");N.params=z;throw N;}C=u}var ba=C}catch(Ca){g.O(Ca),e.clear(),ba=[]}else ba=[];g.BL(this.player,ba);!this.K||this.H||R4(this)||g.Ay(this.A)||g.By(this.A)||(g.Zm(this.ha),ba=T3({uf:0,ue:5,Xf:5,Wf:2,textAlign:0,Gd:0,lang:"en"}),this.V=[ba],e=["Click "," for settings"],this.sa||(C=new g.vu(g.PN()),g.B(this,C),this.sa=C.element),C=ba.end-ba.start,(b=g.aA(this.o))&&this.V.push(new P3(ba.start,
C,0,ba.id,b)),this.V.push(new P3(ba.start,C,0,ba.id,e[0]),new P3(ba.start,C,0,ba.id,this.sa,!0),new P3(ba.start,C,0,ba.id,e[1],!0)),g.BL(this.player,this.V),g.Xm(this.ha));!this.K||this.H||R4(this)||(S4(this,"module-enabled",!0),this.D&&(this.D.o=this.o),(ba=g.R(this.player.app))&&g.jJ(ba.B));this.K=!1}};
g.h.HF=function(a){this.J.push(a);this.aa.ki()};
g.h.IF=function(a){g.bb(this.J,a);this.u instanceof L3&&this.u.C&&g.XU(this.player.app,[a],void 0);this.aa.ki()};
g.h.ZM=function(a){if(a instanceof Q3){var b=this.U[a.id];b&&b.B!=a&&(b.dispose(),delete this.U[a.id],b=null);b||(b=Kpa(this,a))&&(this.U[a.id]=b)}else b=a.windowId,this.W[b]||(this.W[b]=[]),this.W[b].push(a)};
g.h.gN=function(){Lpa(this,this.V);this.V=null};
g.h.bB=function(){this.aa.stop();g.Xb(this.W);this.J.sort(g.uE);var a=this.J;if(this.G){var b=(0,g.Rd)(a,function(c){return-1==this.G.indexOf(c)},this);
b.length&&(a=b)}(0,g.y)(a,this.ZM,this);g.Ib(this.U,function(c,d){this.W[d]?(c.element.parentNode||g.FL(this.player,c.element,4),c.Lh(this.W[d])):(c.dispose(),delete this.U[d])},this)};
g.h.lN=function(){K4(this,{},!0);g.T(this.A.experiments,"web_player_disable_publish_captions_settings_changed_on_reset")||this.player.ma("captionssettingschanged")};
g.h.LD=function(){var a=U4.wb;a={background:a.background,backgroundOpacity:a.backgroundOpacity,charEdgeStyle:a.charEdgeStyle,color:a.color,fontFamily:a.fontFamily,fontSizeIncrement:a.fontSizeIncrement,fontStyle:a.bold&&a.te?3:a.bold?1:a.te?2:0,textOpacity:a.textOpacity,windowColor:U4.windowColor,windowOpacity:U4.windowOpacity};var b=L4(this,"display-settings")||{};null!=b.background&&(a.background=b.background);null!=b.backgroundOverride&&(a.backgroundOverride=b.backgroundOverride);null!=b.backgroundOpacity&&
(a.backgroundOpacity=b.backgroundOpacity);null!=b.backgroundOpacityOverride&&(a.backgroundOpacityOverride=b.backgroundOpacityOverride);null!=b.charEdgeStyle&&(a.charEdgeStyle=b.charEdgeStyle);null!=b.charEdgeStyleOverride&&(a.charEdgeStyleOverride=b.charEdgeStyleOverride);null!=b.color&&(a.color=b.color);null!=b.colorOverride&&(a.colorOverride=b.colorOverride);null!=b.fontFamily&&(a.fontFamily=b.fontFamily);null!=b.fontFamilyOverride&&(a.fontFamilyOverride=b.fontFamilyOverride);null!=b.fontSizeIncrement&&
(a.fontSizeIncrement=b.fontSizeIncrement);null!=b.fontSizeIncrementOverride&&(a.fontSizeIncrementOverride=b.fontSizeIncrementOverride);null!=b.fontStyle&&(a.fontStyle=b.fontStyle);null!=b.fontStyleOverride&&(a.fontStyleOverride=b.fontStyleOverride);null!=b.textOpacity&&(a.textOpacity=b.textOpacity);null!=b.textOpacityOverride&&(a.textOpacityOverride=b.textOpacityOverride);null!=b.windowColor&&(a.windowColor=b.windowColor);null!=b.windowColorOverride&&(a.windowColorOverride=b.windowColorOverride);
null!=b.windowOpacity&&(a.windowOpacity=b.windowOpacity);null!=b.windowOpacityOverride&&(a.windowOpacityOverride=b.windowOpacityOverride);return a};
g.h.gB=function(a,b){var c={};g.Pa(c,L4(this,"display-settings"));g.Pa(c,a);K4(this,c,b);this.player.ma("captionssettingschanged")};
g.h.wt=function(){!this.B&&this.loaded&&(g.Ib(this.U,function(a,b){a.dispose();delete this.U[b]},this),this.bB())};
g.h.Cc=function(a,b){switch(a){case "fontSize":if(isNaN(b))break;var c=g.kd(b,-2,4);this.gB({fontSizeIncrement:c});return c;case "reload":b&&!this.B&&T4(this,this.o,!0);break;case "stickyLoading":void 0!=b&&this.A.xb&&S4(this,"module-enabled",!!b);break;case "track":if(!this.u)return{};if(b){if(this.B)break;if(!g.La(b))break;if(g.Wb(b)){T4(this,null,!0);break}for(var d=D3(this.u.u,!0),e=0;e<d.length;e++){var f=d[e];f.u!=b.languageCode||c&&f.A!=b.languageName||(c=b.translationLanguage?ipa(f,b.translationLanguage):
f)}!c||c==this.o&&this.loaded||T4(this,c,!0)}else return this.loaded&&this.o&&!R4(this)?B3(this.o):{};return"";case "tracklist":return this.u?(0,g.G)(D3(this.u.u,!(!b||!b.includeAsr)),function(k){return B3(k)}):[];
case "translationLanguages":return this.u?this.u.B.map(function(k){return Object.assign({},k)}):[];
case "sampleSubtitles":this.B||void 0==b||Mpa(this,!!b)}};
g.h.getOptions=function(){var a="reload fontSize track tracklist translationLanguages sampleSubtitle".split(" ");this.A.xb&&a.push("stickyLoading");return a};
g.h.GF=function(){var a=this.o;return a?{cc:a.C}:{}};
g.h.LN=function(){this.loaded&&this.o&&!R4(this)?(S4(this,"module-enabled",!1),this.unload(),O4(this,!0)&&T4(this,P4(this),!1)):T4(this,R4(this)||!this.o?Q4(this,!0):this.o,!0)};
g.h.gJ=function(){var a=R4(this);O4(this,a)?T4(this,this.player.getAudioTrack().qm,!1):this.T.captionTracks.length&&(this.loaded&&this.unload(),(this.ba?this.B||this.H:O4(this)||N4(this))&&(a?T4(this,Q4(this),!1):this.load()))};g.sR.captions=M4;})(_yt_player);
